backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/img'
publish_mode: editorial_workflow

collections:
  # Our pages e.g. About
  - name: 'pages'
    label: 'Page'
    filter: {field: "editablepage", value: true}
    folder: 'pages'
    create: false # Change to true to allow editors to create new pages
    slug: '{{slug}}'
    fields:
      - { name: 'layout', widget: 'hidden' }
      - { name: 'navtitle', widget: 'hidden' }
      - { name: 'tags', widget: 'hidden' }
      - { name: 'editablepage', widget: 'hidden' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Homepage
  - name: 'homepage'
    label: 'Homepage'
    filter: {field: "layout", value: "layouts/home.njk"}
    folder: 'pages'
    create: false # Change to true to allow editors to create new pages
    slug: '{{slug}}'
    fields:
      - { name: 'layout', widget: 'hidden' }
      - { name: 'navtitle', widget: 'hidden' }
      - { name: 'editablepage', widget: 'hidden' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Heading', name: 'heading', widget: 'string' }
      - { label: 'Subheading', name: 'subheading', widget: 'string' }
      - { label: 'Body Copy', name: 'bodycopy', widget: 'text' }
  # Photo pages
  - name: 'Photo Collections'
    label: 'Photo Collections'
    filter: {field: "layout", value: "layouts/collection.njk"}
    folder: 'pages'
    create: false # Change to true to allow editors to create new pages
    slug: '{{slug}}'
    fields:
      - { name: 'layout', widget: 'hidden' }
      - { name: 'navtitle', widget: 'hidden' }
      - { name: 'tags', widget: 'hidden' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - { label: 'Alt Text', name: 'alt', widget: 'string' }
          - { label: 'Orientation', name: 'orientation', widget: 'select', options: ['landscape', 'portrait'] }
          - { label: 'Small Image', name: 'image', widget: 'image', hint: '320px tall' }
          - { label: 'Large Image', name: 'large_image', widget: 'image', hint: '1024px wide' }
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string"}