backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  # Our pages e.g. About
  - name: 'pages'
    label: 'Page'
    filter: {field: "editablepage", value: "true"}
    folder: 'pages'
    create: false # Change to true to allow editors to create new pages
    slug: '{{slug}}'
    fields:
      - { name: 'layout', widget: 'hidden' }
      - { name: 'navtitle', widget: 'hidden' }
      - { name: 'tags', widget: 'hidden' }
      - { name: 'editablepage', widget: 'hidden' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'Photo Collections'
    label: 'Photo Collections'
    filter: {field: "layout", value: "layouts/collection.njk"}
    folder: 'pages'
    create: false # Change to true to allow editors to create new pages
    slug: '{{slug}}'
    fields:
      - { name: 'layout', widget: 'hidden' }
      - { name: 'navtitle', widget: 'hidden' }
      - { name: 'tags', widget: 'hidden' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - label: "Collections"
        name: "collections"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subitle", widget: "string"}
          - {label: "Photos", name: "photos", widget: "relation", collection: "photos", searchFields: ["name"], valueField: "name"}
